STATUS_PENDING = "PENDING"
STATUS_IN_PROGRESS = "IN_PROGRESS"
STATUS_COMPLETED = "COMPLETED"
STATUS_FAILED = "FAILED"
STATUS_RETRY_PENDING = "RETRY_PENDING"
STATUS_CANCELLED = "CANCELLED"

STATUS_CHOICES = [
    (STATUS_PENDING, "Pending"),
    (STATUS_IN_PROGRESS, "In Progress"),
    (STATUS_COMPLETED, "Completed"),
    (STATUS_FAILED, "Failed"),
    (STATUS_RETRY_PENDING, "Retry Pending"),
    (STATUS_CANCELLED, "Cancelled"),
]
