name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run application and database using docker-compose
      run: |
        docker-compose up -d

    - name: Run isort
      run: |
        docker-compose exec -T app isort . --check

    - name: Run flake8
      run: |
        docker-compose exec -T app flake8

    - name: Check for missing migrations
      run: |
        docker-compose exec -T app python manage.py makemigrations --check --dry-run

    - name: Run tests
      run: |
        docker-compose exec -T app python manage.py test
